/**
 * PMTiles v3 writer — spec-compliant.
 * Spec: https://github.com/protomaps/PMTiles/blob/main/spec/v3/spec.md
 *
 * Offset encoding (from protomaps/go-pmtiles reference):
 *   write 0        → tile immediately follows the previous tile
 *   write offset+1 → absolute byte offset in tile data section
 */

import { writeFile, mkdir } from 'fs/promises'
import { dirname } from 'path'

// ── Hilbert-curve tile_id ────────────────────────────────────────────────────
export function tileId(z: number, x: number, y: number): bigint {
  if (z === 0) return 0n
  const n = 1 << z
  let rx: number, ry: number
  let xc = x, yc = y
  let d = 0n
  for (let s = n >> 1; s > 0; s >>= 1) {
    rx = (xc & s) > 0 ? 1 : 0
    ry = (yc & s) > 0 ? 1 : 0
    d += BigInt(s * s) * BigInt((3 * rx) ^ ry)
    if (ry === 0) {
      if (rx === 1) { xc = s - 1 - xc; yc = s - 1 - yc }
      ;[xc, yc] = [yc, xc]
    }
  }
  return (4n ** BigInt(z) - 1n) / 3n + d
}

// ── Varint encoding ──────────────────────────────────────────────────────────
function pushVarint(out: number[], n: bigint): void {
  while (n > 127n) {
    out.push(Number(n & 127n) | 128)
    n >>= 7n
  }
  out.push(Number(n))
}

interface Entry {
  tileId:    bigint
  offset:    bigint
  length:    number
  runLength: number
}

// ── Directory serialisation ──────────────────────────────────────────────────
// Matches protomaps/go-pmtiles SerializeEntries encoding exactly:
//   0       → tile immediately follows previous (offset == lastEndOff)
//   N+1     → absolute byte offset N in tile data section
function serializeDir(entries: Entry[]): Buffer {
  const bytes: number[] = []
  let lastId     = 0n
  let lastEndOff = 0n

  for (const e of entries) {
    pushVarint(bytes, e.tileId - lastId)
    lastId = e.tileId

    pushVarint(bytes, BigInt(e.runLength))
    pushVarint(bytes, BigInt(e.length))

    if (e.runLength === 1) {
      if (e.offset === lastEndOff) {
        pushVarint(bytes, 0n)                  // immediately follows
      } else {
        pushVarint(bytes, e.offset + 1n)       // absolute offset, +1 bias
      }
      lastEndOff = e.offset + BigInt(e.length)
    } else {
      pushVarint(bytes, e.offset)              // run: raw absolute offset
    }
  }

  return Buffer.from(bytes)
}

// ── U64 LE helper ────────────────────────────────────────────────────────────
function writeU64(buf: Buffer, off: number, v: bigint): void {
  buf.writeBigUInt64LE(v, off)
}

// ── Public API ───────────────────────────────────────────────────────────────
export interface PMTile {
  z: number
  x: number
  y: number
  data: Uint8Array
}

export interface PMTilesMeta {
  name:    string
  minzoom: number
  maxzoom: number
  bounds:  [number, number, number, number]  // [W, S, E, N]
  center:  [number, number, number]          // [lon, lat, zoom]
}

export async function writePMTiles(
  tiles: PMTile[],
  outputPath: string,
  meta: PMTilesMeta
): Promise<void> {
  // 1 ── Sort non-empty tiles by Hilbert tile_id
  const sorted = tiles
    .filter(t => t.data.length > 0)
    .sort((a, b) => {
      const ia = tileId(a.z, a.x, a.y)
      const ib = tileId(b.z, b.x, b.y)
      return ia < ib ? -1 : ia > ib ? 1 : 0
    })

  // 2 ── Build tile data blob + directory entries
  const dataParts: Buffer[] = []
  const entries: Entry[] = []
  let currentOffset = 0n

  for (const t of sorted) {
    const buf = Buffer.from(t.data)
    entries.push({
      tileId:    tileId(t.z, t.x, t.y),
      offset:    currentOffset,
      length:    buf.length,
      runLength: 1,
    })
    dataParts.push(buf)
    currentOffset += BigInt(buf.length)
  }

  const tileData = Buffer.concat(dataParts)
  const rootDir  = serializeDir(entries)

  const metaJson = Buffer.from(JSON.stringify({
    name:          meta.name,
    description:   `Generated by TileBase`,
    minzoom:       meta.minzoom,
    maxzoom:       meta.maxzoom,
    bounds:        meta.bounds.join(','),
    center:        meta.center.join(','),
    format:        'pbf',
    vector_layers: [{
      id:          meta.name,   // MVT source-layer name = dataset name
      description: meta.name,
      minzoom:     meta.minzoom,
      maxzoom:     meta.maxzoom,
      fields:      {},
    }],
  }), 'utf8')

  // 3 ── Section offsets
  const HEADER  = 127
  const rdOff   = BigInt(HEADER)
  const rdLen   = BigInt(rootDir.length)
  const metaOff = rdOff + rdLen
  const metaLen = BigInt(metaJson.length)
  const leafOff = metaOff + metaLen
  const leafLen = 0n
  const dataOff = leafOff
  const dataLen = BigInt(tileData.length)

  // 4 ── 127-byte header
  const header = Buffer.alloc(HEADER, 0)
  header.write('PMTiles', 0, 'ascii')
  header.writeUInt8(3, 7)                        // version = 3
  // PMTiles v3 spec header — byte offsets from spec.md:
  // https://github.com/protomaps/PMTiles/blob/main/spec/v3/spec.md
  // PMTiles v3 spec header — exact byte offsets per spec.md:
  // https://github.com/protomaps/PMTiles/blob/main/spec/v3/spec.md
  // There is NO tile_data_length field. Offsets after tile_data_offset are:
  //   64 → num_addressed_tiles, 72 → num_tile_entries, 80 → num_tile_contents
  //   88 → clustered, 89 → internal_compression, 90 → tile_compression, 91 → tile_type
  //   92 → min_zoom, 93 → max_zoom
  //   94 → min_lon_e7, 98 → min_lat_e7, 102 → max_lon_e7, 106 → max_lat_e7
  //   110 → center_zoom, 111 → center_lon_e7, 115 → center_lat_e7
  writeU64(header, 8,   rdOff)
  writeU64(header, 16,  rdLen)
  writeU64(header, 24,  metaOff)
  writeU64(header, 32,  metaLen)
  writeU64(header, 40,  leafOff)
  writeU64(header, 48,  leafLen)
  writeU64(header, 56,  dataOff)                              // tile_data_offset
  writeU64(header, 64,  BigInt(sorted.length))               // num_addressed_tiles
  writeU64(header, 72,  BigInt(entries.length))              // num_tile_entries
  writeU64(header, 80,  BigInt(sorted.length))               // num_tile_contents
  header.writeUInt8(1,  88)                                  // clustered
  header.writeUInt8(1,  89)                                  // internal_compression: 1 = none
  header.writeUInt8(1,  90)                                  // tile_compression:     1 = none (raw MVT)
  header.writeUInt8(1,  91)                                  // tile_type:            1 = MVT
  header.writeUInt8(meta.minzoom, 92)
  header.writeUInt8(meta.maxzoom, 93)
  header.writeInt32LE(Math.round(meta.bounds[0] * 1e7), 94)  // min_lon_e7
  header.writeInt32LE(Math.round(meta.bounds[1] * 1e7), 98)  // min_lat_e7
  header.writeInt32LE(Math.round(meta.bounds[2] * 1e7), 102) // max_lon_e7
  header.writeInt32LE(Math.round(meta.bounds[3] * 1e7), 106) // max_lat_e7
  header.writeUInt8(meta.center[2], 110)                      // center_zoom
  header.writeInt32LE(Math.round(meta.center[0] * 1e7), 111) // center_lon_e7
  header.writeInt32LE(Math.round(meta.center[1] * 1e7), 115) // center_lat_e7

  // 5 ── Write
  await mkdir(dirname(outputPath), { recursive: true })
  await writeFile(outputPath, Buffer.concat([header, rootDir, metaJson, tileData]))
}
