/**
 * GET /api/basemap/tilejson.json?datasets=layer1,layer2
 *
 * Returns a TileJSON 3.0.0 descriptor for the merged basemap.
 * Used by QGIS "Add Vector Tile Layer" and ArcGIS Pro.
 */
import { NextRequest, NextResponse } from 'next/server'
import { DATA_DIR } from '@/lib/pipeline'
import { readFile } from 'fs/promises'
import path from 'path'

export async function GET(req: NextRequest) {
  const url = new URL(req.url)
  const datasetsParam = url.searchParams.get('datasets') ?? ''
  const datasets = datasetsParam.split(',').map(s => s.trim()).filter(Boolean)

  if (datasets.length === 0) {
    return new NextResponse('Missing ?datasets= parameter', { status: 400 })
  }

  const origin = `${url.protocol}//${url.host}`

  // Collect per-layer field info from STAC items (best-effort)
  const vectorLayers = await Promise.all(
    datasets.map(async (name) => {
      try {
        const item = JSON.parse(
          await readFile(path.join(DATA_DIR, name, 'item.json'), 'utf8')
        ) as { properties?: Record<string, unknown> }
        const featureCount = (item.properties?.['streamgl:features'] as number | undefined) ?? 0
        return {
          id: name,
          description: `${name} (${featureCount.toLocaleString()} features)`,
          minzoom: 0,
          maxzoom: 14,
          fields: {} as Record<string, string>,
        }
      } catch {
        return { id: name, description: name, minzoom: 0, maxzoom: 14, fields: {} as Record<string, string> }
      }
    })
  )

  const tilejson = {
    tilejson:      '3.0.0',
    name:          `TileBase Basemap — ${datasets.join(', ')}`,
    description:   'Merged vector tile basemap generated by TileBase',
    version:       '1.0.0',
    attribution:   '© TileBase',
    scheme:        'xyz',
    tiles:         [`${origin}/api/basemap/{z}/{x}/{y}?datasets=${datasets.join(',')}`],
    minzoom:       0,
    maxzoom:       14,
    vector_layers: vectorLayers,
  }

  return NextResponse.json(tilejson, {
    headers: {
      'Access-Control-Allow-Origin': '*',
      'Cache-Control': 'public, max-age=60',
    },
  })
}
